### ISSUE TITLE
Mozilla Open Leaders - selection & prep

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/wolo#6]
Selection & Acceptance
- [x] send reminders to select mentees
- [x] create registration form. Include:
  - [x] bio
  - [x] photo (optional)
  - [x] confirm time & job description
- [x] draft acceptance email
- [x] send out acceptance emails, ask to register
  - [x] mention first meeting is next week

Plan for Week 0
- [x] put together agenda
- [x] message hosts w/ updated emcee tips & instructions
- [x] Select mentors to deliver modules
- [x] send out welcome email w/ connection instructions

Plan for Week 2
- [ ] put together agenda
- [ ] message hosts w/ updated emcee tips & instructions
- [ ] Select mentors to deliver modules

**Comment by ryanwarsaw** [comment]
🎉 🕺

**Comment by abbycabs** [comment]
Hahah, thanks @ryanwarsaw 😃

**Comment by abbycabs** [comment]
Registration forms created in the [google drive](https://drive.google.com/drive/folders/0B9UZnVcaoMU6cmdYckVsdW0yRUk)! Not sharing links just in case we get randoms registering 😜

**Comment by abbycabs** [comment]
sent out a small batch of acceptances. Format seems to be messed up, but no one has complained yet... will fix for next batch

**Comment by abbycabs** [comment]
Facilitators Annotated Agenda starting to shape up: https://docs.google.com/document/d/19kCj-iFWWGsIUjIDmgrxHNmRlhzfSYDBdSvPuMLLico/edit#heading=h.pmtz4pabw1j

**Comment by abbycabs** [comment]
closing this and making a week 2 issue :)
